/**
 * @file:   LayoutSBMLError.h
 * @brief:  Implementation of the LayoutSBMLError class
 * @author: Generated by autocreate code
 *
 * <!--------------------------------------------------------------------------
 * This file is part of libSBML.  Please visit http://sbml.org for more
 * information about SBML, and the latest version of libSBML.
 *
 * Copyright (C) 2009-2013 jointly by the following organizations:
 *     1. California Institute of Technology, Pasadena, CA, USA
 *     2. EMBL European Bioinformatics Institute (EBML-EBI), Hinxton, UK
 *
 * Copyright (C) 2006-2008 by the California Institute of Technology,
 *     Pasadena, CA, USA 
 *
 * Copyright (C) 2002-2005 jointly by the following organizations:
 *     1. California Institute of Technology, Pasadena, CA, USA
 *     2. Japan Science and Technology Agency, Japan
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation.  A copy of the license agreement is provided
 * in the file named "LICENSE.txt" included with this software distribution
 * and also available online as http://sbml.org/software/libsbml/license.html
 * ------------------------------------------------------------------------ -->
 */


#ifndef LayoutSBMLError_H__
#define LayoutSBMLError_H__



LIBSBML_CPP_NAMESPACE_BEGIN

BEGIN_C_DECLS


typedef enum
{
	  LayoutUnknownError                      = 6010100
  , LayoutNSUndeclared                      = 6010101 
  , LayoutElementNotInNs                    = 6010102
  , LayoutDuplicateComponentId              = 6010301
  , LayoutAttributeRequiredMissing          = 6020101
  , LayoutAttributeRequiredMustBeBoolean    = 6020102
  , LayoutRequiredFalse                     = 6020103
  , LayoutOnlyOneEachListOf                 = 6020201
  , LayoutNoEmptyListOfs                    = 6020202
  , LayoutLOLayoutsAllowedElements          = 6020203
  , LayoutLOLayoutsAllowedAttributes        = 6020204


}  LayoutSBMLErrorCode_t;

END_C_DECLS

LIBSBML_CPP_NAMESPACE_END

#endif  /*  LayoutSBMLError_h__  */

