var searchData=
[
  ['2_0',['2',['../class_compartment.html#comp-l2',1,'Additional considerations in SBML Level&amp;nbsp;2'],['../class_priority.html#priority-restrictions',1,'Restrictions relaxed in SBML Level&amp;nbsp;3 Version&amp;nbsp;2'],['../class_event_assignment.html#event-asnt-restrictions',1,'Restrictions relaxed in SBML Level&amp;nbsp;3 Version&amp;nbsp;2'],['../class_event.html#l3v2_restrictions',1,'Restrictions relaxed in SBML Level&amp;nbsp;3 Version&amp;nbsp;2'],['../class_delay.html#delay-restrictions',1,'Restrictions relaxed in SBML Level&amp;nbsp;3 Version&amp;nbsp;2'],['../class_event.html#sbml-l2',1,'SBML Level 2'],['../class_s_b_m_l_extension.html#sbmlextension-l2-special',1,'Special handling for SBML Level&amp;nbsp;2'],['../class_species_reference.html#spr-l2',1,'SpeciesReference in SBML Level 2'],['../class_stoichiometry_math.html#l2-stoichiometries',1,'Stoichiometries in SBML Level 2']]],
  ['2_201_20define_20protected_20data_20members_1',['2.1 Define protected data members',['../classdoc__extension__sbaseplugin.html#sbp-protected',1,'']]],
  ['2_201_20override_20sbaseplugin_20class_20related_20methods_2',['2.1 Override SBasePlugin class-related methods',['../classdoc__extension__sbmldocumentplugin.html#sdp-class',1,'']]],
  ['2_201_20using_20copydetails_3',['4.2.1 Using &quot;@copydetails&quot;',['../libsbml-coding.html#coding-copydetails',1,'']]],
  ['2_202_20determine_20the_20necessary_20value_20of_20the_20required_20attribute_4',['2.2 Determine the necessary value of the &quot;required&quot; attribute',['../classdoc__extension__sbmldocumentplugin.html#sdp-required',1,'']]],
  ['2_202_20override_20sbaseplugin_20class_20related_20methods_5',['2.2 Override SBasePlugin class-related methods',['../classdoc__extension__sbaseplugin.html#sbp-class-methods',1,'']]],
  ['2_202_20using_20copydoc_6',['4.2.2 Using &quot;@copydoc&quot;',['../libsbml-coding.html#coding-copydoc',1,'']]],
  ['2_203_20define_20protected_20data_20members_7',['2.3 Define protected data members',['../classdoc__extension__sbmldocumentplugin.html#sdp-protected',1,'']]],
  ['2_203_20override_20sbaseplugin_20virtual_20methods_20for_20attributes_8',['2.3 Override SBasePlugin virtual methods for attributes',['../classdoc__extension__sbaseplugin.html#sbp-methods-attribs',1,'']]],
  ['2_203_20using_20htmlinclude_9',['4.2.3 Using &quot;@htmlinclude&quot;',['../libsbml-coding.html#coding-htmlinclude',1,'']]],
  ['2_204_20override_20sbaseplugin_20virtual_20methods_20for_20subcomponents_10',['2.4 Override SBasePlugin virtual methods for subcomponents',['../classdoc__extension__sbaseplugin.html#sbp-methods-elem',1,'']]],
  ['2_204_20override_20virtual_20methods_20for_20attributes_11',['2.4 Override virtual methods for attributes',['../classdoc__extension__sbmldocumentplugin.html#sdp-methods-attribs',1,'']]],
  ['2_205_20override_20sbaseplugin_20virtual_20methods_20for_20xml_20namespaces_12',['2.5 Override SBasePlugin virtual methods for XML namespaces',['../classdoc__extension__sbaseplugin.html#sbp-methods-xmlns',1,'']]],
  ['2_205_20override_20virtual_20methods_20for_20subcomponents_13',['2.5 Override virtual methods for subcomponents',['../classdoc__extension__sbmldocumentplugin.html#sdp-methods-elem',1,'']]],
  ['2_206_20implement_20additional_20methods_20as_20needed_14',['2.6 Implement additional methods as needed',['../classdoc__extension__sbaseplugin.html#sbp-methods-hooks',1,'']]],
  ['2_206_20override_20virtual_20methods_20for_20xml_20namespaces_15',['2.6 Override virtual methods for XML namespaces',['../classdoc__extension__sbmldocumentplugin.html#sdp-methods-xmlns',1,'']]],
  ['2_207_20implement_20additional_20methods_20as_20needed_16',['2.7 Implement additional methods as needed',['../classdoc__extension__sbmldocumentplugin.html#sdp-methods-hooks',1,'']]],
  ['2_20basic_20guidelines_20for_20libsbml_17',['2. Basic guidelines for libSBML',['../libsbml-coding.html#coding-basic',1,'']]],
  ['2_20create_20a_20sbaseplugin_20subclass_20for_20each_20extended_20sbml_20component_18',['2. Create a SBasePlugin subclass for each extended SBML component',['../classdoc__extension__sbaseplugin.html#sbp-implement',1,'']]],
  ['2_20create_20the_20sbmldocumentplugin_20subclass_19',['2. Create the SBMLDocumentPlugin subclass',['../classdoc__extension__sbmldocumentplugin.html#sdp-implement',1,'']]],
  ['2_20define_20methods_20returning_20package_20version_20information_20',['2. Define methods returning package version information',['../classdoc__extension__sbmlextension.html#ext-version-methods',1,'']]],
  ['2_20derive_20classes_20from_20sbaseplugin_21',['2. Derive classes from SBasePlugin',['../libsbml-howto-implement-extension.html#implem-sbaseplugin',1,'']]],
  ['2_20generating_20python_20docs_22',['6.2 Generating Python docs',['../libsbml-coding.html#doc-process-python',1,'']]],
  ['2_20guidelines_20for_20cpp_20files_23',['3.2 Guidelines for .cpp files',['../libsbml-coding.html#coding-doc-cpp',1,'']]],
  ['2_20instantiate_20a_20template_20instance_24',['2. Instantiate a template instance',['../classdoc__extension__sbmlextensionnamespaces.html#sen-instantiate',1,'']]],
  ['2_20linking_20with_20or_20importing_20libsbml_25',['2. Linking with or importing libSBML',['../libsbml-accessing.html#config-software',1,'']]],
  ['2_20referring_20to_20libsbml_20pure_20functions_26',['4.1.2 Referring to libSBML pure functions',['../libsbml-coding.html#coding-function-refs',1,'']]],
  ['2_20reusing_20common_20text_27',['4.2 Reusing common text',['../libsbml-coding.html#coding-reusing-text',1,'']]],
  ['2_20versions_20nbsp_201_20ndash_202_28',['The spatialSizeUnits attribute in SBML Level&amp;nbsp;2 Versions&amp;nbsp;1&amp;ndash;2',['../class_species.html#species-other',1,'']]],
  ['2_20versions_20nbsp_202_20ndash_204_29',['The speciesType attribute in SBML Level&amp;nbsp;2 Versions&amp;nbsp;2&amp;ndash;4',['../class_species.html#species-l2-type',1,'']]]
];
