#ifdef USE_DYN

SBMLCONSTRUCTOR_EXCEPTION(DynPkgNamespaces)
SBMLCONSTRUCTOR_EXCEPTION(DynElement)
SBMLCONSTRUCTOR_EXCEPTION(SpatialComponent)
SBMLCONSTRUCTOR_EXCEPTION(ListOfDynElements)
SBMLCONSTRUCTOR_EXCEPTION(ListOfSpatialComponents)

#endif // USE_DYN 

