package:
  name: ${NAME}
  version: "${PACKAGE_VERSION}"

source:
  fn: ${NAME}-${PACKAGE_VERSION}.tar.gz
  url: https://pypi.python.org/packages/source/p/${NAME}/${NAME}-${PACKAGE_VERSION}.tar.gz
  
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-libsbml = python-libsbml:main
    #
    # Would create an entry point called python-libsbml that calls python-libsbml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - libsbml

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sbml.org
  license: LGPL
  summary: 'LibSBML Python API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
