(in-package :cl-user)
(defpackage "CPARSE"
  (:use "COMMON-LISP")
  (:export "VOID" "UNSIGNED" "INT" "UNSIGNED-INT" "LONG"
	   "UNSIGNED-LONG" "LONG-LONG" "UNSIGNED-LONG-LONG"
	   "SHORT" "UNSIGNED-SHORT" "CFLOAT" "DOUBLE" "CHAR"
	   "SIGNED-CHAR" "UNSIGNED-CHAR" "VALUE"
	   "C-TYPE"
	   "POINTER-TYPE" "TO"
	   "ARRAY-TYPE" "OF" "LEN"
	   "FUNC-TYPE" "RETURN-TYPE" "ARGS"
	   "SCOPE" "OBJECTS" "STRUCT-TAGS" "STRUCT-MEMBERS" "OUTER-SCOPE"
	   "COMPOUND-TYPE"
	   "STRUCT-TYPE" "UNION-TYPE" "MEMBERS" "TAG"
	   "ENUM-TYPE" "ENUMERATORS"
	   "STDARG-TYPE" "TYPEDEF-TYPE" "DEFINED-TYPE"
	   "CPARSE-STREAM" "CPARSE-STRING" "CPARSE-FILE"
	   "CPARSE-ERROR" "CPARSE-ERROR-FILE-NAME" "CPARSE-ERROR-LINE-NUMBER"
	   "CPARSE-ERROR-FORMAT-STRING" "CPARSE-ERROR-FORMAT-ARGUMENTS")
  (:shadow "CHAR" "STREAM" "PACKAGE")
  )


(in-package "CPARSE")
